### ISSUE TITLE
Lemmatization default to noun

### ISSUE THREAD

**Issue by rth** [ClaudeCoulombe/FrenchLefffLemmatizer#4]
Currently the default lemmatization defaults to noun,
```py
>>> lem = FrenchLefffLemmatizer()
>>> lem.lemmatize('pourriez')
'pourriez'
>>> lem.lemmatize('pourriez', 'all')
[('pouvoir', 'v')]
```

It would be nice to have an option to pass `pos=None` that would do `pos='all'` and then if there is 1 response in the list, return it; otherwise return the word unchanged.

Or maybe add another method for it?

**Comment by ClaudeCoulombe** [comment]
Sorry for my very late answer.

You've made a nice suggestion but the reason for this default FrenchLefffLemmatizer behavior was to maintain the compatibility of the API with the WordNet lemmatizer. 

` > import nltk`
`> from nltk.stem import WordNetLemmatizer`
`> wn_lem = WordNetLemmatizer()`
`> wn_lem.lemmatize("bought")`
`> 'bought'`
`> wn_lem.lemmatize("bought",'v')`
`> 'buy'`
