### ISSUE TITLE
Lemmatisation for proper nouns

### ISSUE THREAD

**Issue by EzrielS** [ClaudeCoulombe/FrenchLefffLemmatizer#5]
I think there is a problem with the lemmatizer when the result is just a proper nouns:
for example, where I test : 
`lemmatizer.lemmatize("Barcelone", 'all')`
I get :
`('Barcelone', 'np')`
i.e, a tuple, where if I test with:
`lemmatizer.lemmatize("tracteur", 'all')`
I get:
`[('tracteur', 'nc')]`
i.e., a tuple in a list.

**Comment by ClaudeCoulombe** [comment]
Sorry for my very late answer ;-(

You've found an inconsistency in the API, so I've fixed it.

Thanks a lot
